ERROR - 2024-11-25 16:53:34 --> Table 'scai.logger_auth_cm' doesn't exist
ERROR - 2024-11-25 16:53:34 --> Table 'scai.logger_auth_cm' doesn't exist
CRITICAL - 2024-11-25 16:53:34 --> Table 'scai.logger_auth_cm' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `logger_auth_cm` (`date`, `data`, `id_user`, `details`, `type`, `action`) VALUES (\'2024-11-25 04:11:34\', \'{\\"name\\":\\"LISTA INSCRITOS (1).xlsx\\",\\"full_path\\":\\"LISTA INSCRITOS (1).xlsx\\",\\"type\\":\\"application\\\\/vnd.openxmlformats-officedocument.spreadsheetml.sheet\\",\\"tmp_name\\":\\"C:\\\\\\\\xampp\\\\\\\\tmp\\\\\\\\php1684.tmp\\",\\"error\\":0,\\"size\\":21789}\', NULL, \'{\\"operation\\":\\"fail\\",\\"msj\\":\\"hubo error al leer el archivo\\",\\"description\\":\\" mysqli_sql_exception: Table \\\'scai.logger_auth_cm\\\' doesn\\\'t exist in C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\MySQLi\\\\\\\\Connection.php:292\\\\nStack trace:\\\\n#0 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\MySQLi\\\\\\\\Connection.php(292): mysqli->query(\\\'INSERT INTO `lo...\\\', 0)\\\\n#1 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\BaseConnection.php(695): CodeIgniter\\\\\\\\Database\\\\\\\\MySQLi\\\\\\\\Connection->execute(\\\'INSERT INTO `lo...\\\')\\\\n#2 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\BaseConnection.php(609): CodeIgniter\\\\\\\\Database\\\\\\\\BaseConnection->simpleQuery(\\\'INSERT INTO `lo...\\\')\\\\n#3 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\BaseBuilder.php(1904): CodeIgniter\\\\\\\\Database\\\\\\\\BaseConnection->query(\\\'INSERT INTO `lo...\\\', Array, false)\\\\n#4 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Model.php(278): CodeIgniter\\\\\\\\Database\\\\\\\\BaseBuilder->insert()\\\\n#5 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\BaseModel.php(738): CodeIgniter\\\\\\\\Model->doInsert(Array)\\\\n#6 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Model.php(666): CodeIgniter\\\\\\\\BaseModel->insert(Array, true)\\\\n#7 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\app\\\\\\\\Helpers\\\\\\\\logger_helper.php(12): CodeIgniter\\\\\\\\Model->insert(Array)\\\\n#8 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\app\\\\\\\\Controllers\\\\\\\\ExcelLector.php(352): logger(\\\'{\\\\\\"name\\\\\\":\\\\\\"LISTA ...\\\', NULL, \\\'{\\\\\\"operation\\\\\\":\\\\\\"s...\\\', \\\'sucess\\\', \\\'recibe\\\')\\\\n#9 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\CodeIgniter.php(896): App\\\\\\\\Controllers\\\\\\\\ExcelLector->recibe()\\\\n#10 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\CodeIgniter.php(466): CodeIgniter\\\\\\\\CodeIgniter->runController(Object(App\\\\\\\\Controllers\\\\\\\\ExcelLector))\\\\n#11 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\CodeIgniter.php(349): CodeIgniter\\\\\\\\CodeIgniter->handleRequest(NULL, Object(Config\\\\\\\\Cache), false)\\\\n#12 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\index.php(67): CodeIgniter\\\\\\\\CodeIgniter->run()\\\\n#13 {main}\\"}\', \'error\', \'recibe\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(695): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `logger_auth_cm` (`date`, `data`, `id_user`, `details`, `type`, `action`) VALUES (\'2024-11-25 04:11:34\', \'{\\"name\\":\\"LISTA INSCRITOS (1).xlsx\\",\\"full_path\\":\\"LISTA INSCRITOS (1).xlsx\\",\\"type\\":\\"application\\\\/vnd.openxmlformats-officedocument.spreadsheetml.sheet\\",\\"tmp_name\\":\\"C:\\\\\\\\xampp\\\\\\\\tmp\\\\\\\\php1684.tmp\\",\\"error\\":0,\\"size\\":21789}\', NULL, \'{\\"operation\\":\\"fail\\",\\"msj\\":\\"hubo error al leer el archivo\\",\\"description\\":\\" mysqli_sql_exception: Table \\\'scai.logger_auth_cm\\\' doesn\\\'t exist in C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\MySQLi\\\\\\\\Connection.php:292\\\\nStack trace:\\\\n#0 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\MySQLi\\\\\\\\Connection.php(292): mysqli->query(\\\'INSERT INTO `lo...\\\', 0)\\\\n#1 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\BaseConnection.php(695): CodeIgniter\\\\\\\\Database\\\\\\\\MySQLi\\\\\\\\Connection->execute(\\\'INSERT INTO `lo...\\\')\\\\n#2 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\BaseConnection.php(609): CodeIgniter\\\\\\\\Database\\\\\\\\BaseConnection->simpleQuery(\\\'INSERT INTO `lo...\\\')\\\\n#3 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\BaseBuilder.php(1904): CodeIgniter\\\\\\\\Database\\\\\\\\BaseConnection->query(\\\'INSERT INTO `lo...\\\', Array, false)\\\\n#4 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Model.php(278): CodeIgniter\\\\\\\\Database\\\\\\\\BaseBuilder->insert()\\\\n#5 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\BaseModel.php(738): CodeIgniter\\\\\\\\Model->doInsert(Array)\\\\n#6 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Model.php(666): CodeIgniter\\\\\\\\BaseModel->insert(Array, true)\\\\n#7 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\app\\\\\\\\Helpers\\\\\\\\logger_helper.php(12): CodeIgniter\\\\\\\\Model->insert(Array)\\\\n#8 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\app\\\\\\\\Controllers\\\\\\\\ExcelLector.php(352): logger(\\\'{\\\\\\"name\\\\\\":\\\\\\"LISTA ...\\\', NULL, \\\'{\\\\\\"operation\\\\\\":\\\\\\"s...\\\', \\\'sucess\\\', \\\'recibe\\\')\\\\n#9 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\CodeIgniter.php(896): App\\\\\\\\Controllers\\\\\\\\ExcelLector->recibe()\\\\n#10 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\CodeIgniter.php(466): CodeIgniter\\\\\\\\CodeIgniter->runController(Object(App\\\\\\\\Controllers\\\\\\\\ExcelLector))\\\\n#11 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\CodeIgniter.php(349): CodeIgniter\\\\\\\\CodeIgniter->handleRequest(NULL, Object(Config\\\\\\\\Cache), false)\\\\n#12 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\index.php(67): CodeIgniter\\\\\\\\CodeIgniter->run()\\\\n#13 {main}\\"}\', \'error\', \'recibe\')')
 3 SYSTEMPATH\Database\BaseConnection.php(609): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `logger_auth_cm` (`date`, `data`, `id_user`, `details`, `type`, `action`) VALUES (\'2024-11-25 04:11:34\', \'{\\"name\\":\\"LISTA INSCRITOS (1).xlsx\\",\\"full_path\\":\\"LISTA INSCRITOS (1).xlsx\\",\\"type\\":\\"application\\\\/vnd.openxmlformats-officedocument.spreadsheetml.sheet\\",\\"tmp_name\\":\\"C:\\\\\\\\xampp\\\\\\\\tmp\\\\\\\\php1684.tmp\\",\\"error\\":0,\\"size\\":21789}\', NULL, \'{\\"operation\\":\\"fail\\",\\"msj\\":\\"hubo error al leer el archivo\\",\\"description\\":\\" mysqli_sql_exception: Table \\\'scai.logger_auth_cm\\\' doesn\\\'t exist in C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\MySQLi\\\\\\\\Connection.php:292\\\\nStack trace:\\\\n#0 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\MySQLi\\\\\\\\Connection.php(292): mysqli->query(\\\'INSERT INTO `lo...\\\', 0)\\\\n#1 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\BaseConnection.php(695): CodeIgniter\\\\\\\\Database\\\\\\\\MySQLi\\\\\\\\Connection->execute(\\\'INSERT INTO `lo...\\\')\\\\n#2 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\BaseConnection.php(609): CodeIgniter\\\\\\\\Database\\\\\\\\BaseConnection->simpleQuery(\\\'INSERT INTO `lo...\\\')\\\\n#3 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Database\\\\\\\\BaseBuilder.php(1904): CodeIgniter\\\\\\\\Database\\\\\\\\BaseConnection->query(\\\'INSERT INTO `lo...\\\', Array, false)\\\\n#4 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Model.php(278): CodeIgniter\\\\\\\\Database\\\\\\\\BaseBuilder->insert()\\\\n#5 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\BaseModel.php(738): CodeIgniter\\\\\\\\Model->doInsert(Array)\\\\n#6 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\Model.php(666): CodeIgniter\\\\\\\\BaseModel->insert(Array, true)\\\\n#7 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\app\\\\\\\\Helpers\\\\\\\\logger_helper.php(12): CodeIgniter\\\\\\\\Model->insert(Array)\\\\n#8 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\app\\\\\\\\Controllers\\\\\\\\ExcelLector.php(352): logger(\\\'{\\\\\\"name\\\\\\":\\\\\\"LISTA ...\\\', NULL, \\\'{\\\\\\"operation\\\\\\":\\\\\\"s...\\\', \\\'sucess\\\', \\\'recibe\\\')\\\\n#9 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\CodeIgniter.php(896): App\\\\\\\\Controllers\\\\\\\\ExcelLector->recibe()\\\\n#10 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\CodeIgniter.php(466): CodeIgniter\\\\\\\\CodeIgniter->runController(Object(App\\\\\\\\Controllers\\\\\\\\ExcelLector))\\\\n#11 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\vendor\\\\\\\\codeigniter4\\\\\\\\framework\\\\\\\\system\\\\\\\\CodeIgniter.php(349): CodeIgniter\\\\\\\\CodeIgniter->handleRequest(NULL, Object(Config\\\\\\\\Cache), false)\\\\n#12 C:\\\\\\\\xampp\\\\\\\\htdocs\\\\\\\\controlaccesos\\\\\\\\index.php(67): CodeIgniter\\\\\\\\CodeIgniter->run()\\\\n#13 {main}\\"}\', \'error\', \'recibe\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1904): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logger_auth_cm` (`date`, `data`, `id_user`, `details`, `type`, `action`) VALUES (:date:, :data:, :id_user:, :details:, :type:, :action:)', [...], false)
 5 SYSTEMPATH\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(738): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(666): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Helpers\logger_helper.php(12): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\ExcelLector.php(365): logger('{"name":"LISTA INSCRITOS (1).xlsx","full_path":"LISTA INSCRITOS (1).xlsx","type":"application\\/vnd.openxmlformats-officedocument.spreadsheetml.sheet","tmp_name":"C:\\\\xampp\\\\tmp\\\\php1684.tmp","error":0,"size":21789}', null, '{"operation":"fail","msj":"hubo error al leer el archivo","description":" mysqli_sql_exception: Table \'scai.logger_auth_cm\' doesn\'t exist in C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\vendor\\\\codeigniter4\\\\framework\\\\system\\\\Database\\\\MySQLi\\\\Connection.php:292\\nStack trace:\\n#0 C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\vendor\\\\codeigniter4\\\\framework\\\\system\\\\Database\\\\MySQLi\\\\Connection.php(292): mysqli->query(\'INSERT INTO `lo...\', 0)\\n#1 C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\vendor\\\\codeigniter4\\\\framework\\\\system\\\\Database\\\\BaseConnection.php(695): CodeIgniter\\\\Database\\\\MySQLi\\\\Connection->execute(\'INSERT INTO `lo...\')\\n#2 C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\vendor\\\\codeigniter4\\\\framework\\\\system\\\\Database\\\\BaseConnection.php(609): CodeIgniter\\\\Database\\\\BaseConnection->simpleQuery(\'INSERT INTO `lo...\')\\n#3 C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\vendor\\\\codeigniter4\\\\framework\\\\system\\\\Database\\\\BaseBuilder.php(1904): CodeIgniter\\\\Database\\\\BaseConnection->query(\'INSERT INTO `lo...\', Array, false)\\n#4 C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\vendor\\\\codeigniter4\\\\framework\\\\system\\\\Model.php(278): CodeIgniter\\\\Database\\\\BaseBuilder->insert()\\n#5 C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\vendor\\\\codeigniter4\\\\framework\\\\system\\\\BaseModel.php(738): CodeIgniter\\\\Model->doInsert(Array)\\n#6 C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\vendor\\\\codeigniter4\\\\framework\\\\system\\\\Model.php(666): CodeIgniter\\\\BaseModel->insert(Array, true)\\n#7 C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\app\\\\Helpers\\\\logger_helper.php(12): CodeIgniter\\\\Model->insert(Array)\\n#8 C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\app\\\\Controllers\\\\ExcelLector.php(352): logger(\'{\\"name\\":\\"LISTA ...\', NULL, \'{\\"operation\\":\\"s...\', \'sucess\', \'recibe\')\\n#9 C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\vendor\\\\codeigniter4\\\\framework\\\\system\\\\CodeIgniter.php(896): App\\\\Controllers\\\\ExcelLector->recibe()\\n#10 C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\vendor\\\\codeigniter4\\\\framework\\\\system\\\\CodeIgniter.php(466): CodeIgniter\\\\CodeIgniter->runController(Object(App\\\\Controllers\\\\ExcelLector))\\n#11 C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\vendor\\\\codeigniter4\\\\framework\\\\system\\\\CodeIgniter.php(349): CodeIgniter\\\\CodeIgniter->handleRequest(NULL, Object(Config\\\\Cache), false)\\n#12 C:\\\\xampp\\\\htdocs\\\\controlaccesos\\\\index.php(67): CodeIgniter\\\\CodeIgniter->run()\\n#13 {main}"}', 'error', 'recibe')
10 SYSTEMPATH\CodeIgniter.php(896): App\Controllers\ExcelLector->recibe()
11 SYSTEMPATH\CodeIgniter.php(466): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExcelLector))
12 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-11-25 18:43:45 --> syntax error, unexpected token "catch", expecting "function" or "const"
in APPPATH\Controllers\ExcelLector.php on line 377.
 1 SYSTEMPATH\Autoloader\Autoloader.php(261): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\ExcelLector.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(239): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\ExcelLector')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\ExcelLector')
 4 SYSTEMPATH\CodeIgniter.php(846): class_exists('\\App\\Controllers\\ExcelLector', true)
 5 SYSTEMPATH\CodeIgniter.php(453): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
